### PR TITLE
Fix bytecode compatible back to 52(JDK8)

### PR DESCRIPTION
**Pull request by shifujun**
This project need JDK 11 to compile, but target to JDK 8.

IDEA need uncheck "use --release" in Preferences |
Build, Execution, Deployment | Compiler | Java Compiler
, to build success.

fix #470

### CODE REVIEW

**Review by wuwen5 — CHANGES_REQUESTED** [review]
This should not be submitted, it is in `.gitignore`

**Comment by shifujun** [comment]
> `.idea/compiler.xml` This should not be submitted, it is in `.gitignore`

IDEA need it. I can't find another way to make IDEA auto import work.

In addition, being in `.gitignore` does not prevent it from working properly. Users will usually no longer trigger modifications to it.

**Comment by wuwen5** [comment]
This is just a configuration file for a personal local development tool that is independent of the source code and build，It's generally recommended not to include IDE-specific configuration files in the repository, as they are specific to each developer's local environment.

**Comment by shifujun** [comment]
1. Adding no IDE configuration to git is also my goal.
2. Popular IDE（IDEA）can import this project is very helpful for getting more contributors.
3. Compile JDK 9 source to JDK 8 target is not standard, so I can't blame IDEA cannot auto import.
4. Not all IDE config file is personal relative. `.idea/compiler.xml` is generic.

**Comment by hazendaz** [comment]
@shifujun How about you bridge the divide here.  No one wants to see anything .idea checked in.  So why not add to the README for IDEA users they need to do that and put the same in change log once release is tagged and updated?  That seems like a compromise that will fix this back for now.

For reference, I'm over at https://github.com/mybatis/ and we shade this and cannot upgrade to this version without raising to java 11.  We are still discussing where we want to raise but this report https://newrelic.com/resources/report/2023-state-of-the-java-ecosystem shows there is still a lot of life left with java 8.  So I think don't press people to have idea configuration files on a repo.  That isn't helpful, but if you need them to know how, document it instead.

**Review by wuwen5 — APPROVED** [review]

**Review by LowAmmo — APPROVED** [review]

**Review by vikinghawk — APPROVED** [review]

**Comment by LowAmmo** [comment]
@wuwen5 - We need to get this fix to get some of our applications working again. Any chance this can be merged and released ASAP?

**Review by bjenning04 — APPROVED** [review]

**Comment by wuwen5** [comment]
@LowAmmo I'm not the project member, but I share your sense of urgency. I hope the fix can be merged and released as soon as possible.

@chibash  Could you help us release the version?

**Comment by chibash** [comment]
I'll release this by this weekend.  Is this too late?

**Comment by LowAmmo** [comment]
@chibash - I appreciate the quick response on the merge! Thank you!

At least for me, the sooner the better, but I totally understand if you need to wait a few days.

-Thanks!

**Pull request merged**
