### PR TITLE
Added call back feature to CtBehaviour

### PR DESCRIPTION
**Pull request by m8rten**
I created a call back feature for CtBehaviour insertion methods.

If it is something thats interesting for the jboss-javassist repository I can add unit tests and maybe also improve the Callback class.

We use anonymous Callback classes for instrumentation, it's actually quite neat.

Best regards,
Mårten

### CODE REVIEW

**Comment by chibash** [comment]
Hi,

The proposed feature looks useful but could you implement it without modifying CtBehavior?
I want to keep javassist.* classes independent of javassist.tools.*
Maybe moving insertBefore(Callback c) to Callback class as a static method?

**Comment by m8rten** [comment]
Hi,

Made CtBehaviour independent. Added utility methods in Callback. Created test case.

**Comment by chibash** [comment]
Looks good.  No further modification?

**Comment by m8rten** [comment]
Cool. Not right now.

Skickat från min iPhone

**Comment by chibash** [comment]
Don't you mind adding the normal copyright notice to the code?
It says the copyright is hold by me but the code is surely distributed under the open source license.
You can add @author to the code if you want.

**Comment by m8rten** [comment]
Sure!

**Pull request merged**
