### PR TITLE
JASSIST-271 Allow running on Java 11 by falling back to ClassLoader.defineClass for Java > 10

### PR DESCRIPTION
**Pull request by beikov**
https://issues.jboss.org/browse/JASSIST-271

### CODE REVIEW

**Comment by luengnat** [comment]
any plan to release this soon?

**Comment by chibash** [comment]
I can do so when you need.  Immediately?

**Comment by sited-project** [comment]
Yes, please, really need the fix. I could not find a way to solve the split package issue of java.transaction for Java 10. Even gradle compiles, Intellij IDEA will still show errors.

**Comment by joschi** [comment]
@chibash Same here. It would be really great if you could release a new version of Javassist with this PR.

In my specific case it's about making [Dropwizard](https://github.com/dropwizard/dropwizard) run with Java 11-ea.

**Comment by chibash** [comment]
I've released it.  It will be available from maven soon.

**Comment by joschi** [comment]
@chibash Awesome, thank you very much!

**Pull request merged**
