### PR TITLE
[#171] Allow running on JDK 8 and possibly on JDK 7 as well. Fixes #171

### LINKED ISSUE #171: Compatibility to JDK 8 and JDK 9 at the same time?
Hi, is the next version supposed to support JDK9 and JDK8? I'm currently experiencing this exception when running the master on JDK8. Or is there a 'special' way i need to build the jar? 

```java
Caused by: java.lang.NoClassDefFoundError: java/lang/StackWalker$Option
	at javassist.util.proxy.DefineClassHelper$SecuredPrivileged$1.<init>(DefineClassHelper.java:67)
	at javassist.util.proxy.DefineClassHelper$SecuredPrivileged.<clinit>(DefineClassHelper.java:38)
	at javassist.util.proxy.DefineClassHelper.<clinit>(DefineClassHelper.java:177)
	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:128)
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:552)
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:537)
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:473)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:444)
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:75)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:163)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58)
	... 131 more
Caused by: java.lang.ClassNotFoundException: java.lang.StackWalker$Option
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.jboss.modules.JDKSpecific.getSystemClass(JDKSpecific.java:183)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:397)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	... 143 more
```

P.S Would it be possible to get a build of the 'master' somewhere? So i don't have to build it? Unfortunately the latest GA release causes a NPE (which has been fixed in a later commit)

### PR DESCRIPTION
**Pull request by beikov**
Fix for #171

### CODE REVIEW

**Comment by nickl-** [comment]
I see what you are trying to accomplish, not sure why it involves obfuscating the `IllegalAccessError` though.

**Comment by beikov** [comment]
Maybe I'm missing the exact line you are referring to, but `IllegalAccessError` isn't a subtype of `Exception` but only of `Error` and thus also `Throwable` so AFAICT there is no obfuscation.

**Comment by nickl-** [comment]
@beikov you are correct, my mistake. `Error` is not caught by `Exception`. My bad!

I still can't help wondering if we're doctoring the symptoms instead of fixing the problem. Why does JDK8 have to interpret the newer api calls? Can that not be avoided?

**Comment by beikov** [comment]
Well, because the JVM loads referenced classes due to the initialization of the enum and on Java 8 the StackWalker isn't available. Another possible fix is to make use of the MR-JAR feature, but that would require changes in the build which I wanted to avoid.

**Comment by nickl-** [comment]
Oh crap so the enum gets completely referenced when initialized... grrrr that's annoying. 

So basically this makes switching capabilities as an enum useless, we should take the whole `SecuredPrivileged ` as an enum implementation back to the drawing board and refactor it into a class or something. 

Damn that sux! Worked great in theory... =(

**Comment by jplock** [comment]
@chibash when can this be included into a future release?

**Comment by chibash** [comment]
OK, what about releasing within a week unless I see an objection?

**Comment by johnou** [comment]
@chibash sounds good, thanks!

**Comment by chibash** [comment]
I've released 3.23.1-GA.  It will be soon available from maven as well.

**Pull request merged**
