### PR TITLE
Added new feature.

### PR DESCRIPTION
**Pull request by dalgarins**
Now you can change the Strings within the ConstPool, with methods
SetStringInfo().

### CODE REVIEW

**Comment by dalgarins** [comment]
This new feature is necessary, when you have to modify a String Hardcoded within the code and insert the code difficult for any error caused.

**Comment by nickl-** [comment]
I wish this jumped out at me and I understood what you are trying to accomplish but mostly why you need to implement everything to get it done. Is there nothing in ConstPool which you can reuse to get the index maybe, or add the Item?

What is the significance with **set** there is no other set method in this class they are mostly **get** or **add**. What are you trying to accomplish here which `addStringInfo` doesn't do?

https://github.com/jboss-javassist/javassist/blob/79a0634e2263ac0176cce5a84de50f662b8fe88c/src/main/javassist/bytecode/ConstPool.java#L1078-L1090

Excuse my ignorance if I am missing something obvious.

**Comment by dalgarins** [comment]
There were 3 methods, setStringInfo and addStringInfo, at that time I needed to be able to modify the constpool in an easier way, to replace a string inside the constpool, because the implementations I had found to replace a string within a class seemed very difficult and tedious , in this way it is easier to change a string. and I decided to push in case someone needed to do the same.

**Comment by chibash** [comment]
CONSTANT_String_info may be shared among several bytecode instructions.
So changing it will be dangerous since none is sure that the actual effect of the change is
exactly what she needs.  I recommend to add a new String_info and garbage collect unused
String_info.

**Comment by nickl-** [comment]
That makes sense, replace the reference instead of modifying it. 

@chibash you should please close these or at least mark them as "won't commit" so we don't waste time reviewing PRs that are obsolete.

**Comment by nickl-** [comment]
**Suggest close PR
Reason: Preferred functionality available**

**Pull request closed without merging**
