### PR TITLE
New Function CtClass#removeNestedClass(String) to remove an InnerClass

### PR DESCRIPTION
**Pull request by kuzukami**
I want to use the javassist to shrink my code becuase  the quality of defacto shrinker in java is not so reliable at least in java 8. I wrote a new Function to remove a signature of InnerClass in a java class. This function is a very basic operation for byte code shrinker to shrink the inner-class relation. I also wrote some tests for new function.

### CODE REVIEW

**Comment by hamzaxx** [comment]
This is poorly formatted, you should put some time into formatting it correctly.

**Comment by kuzukami** [comment]
In my eclipse environment, the formatting is not so poor. How do I do. Is there some auto formatting tools or setting for this project?

**Comment by chibash** [comment]
By hand, please! :-p

**Comment by kuzukami** [comment]
I'll pull-req again.

**Pull request closed without merging**
