### PR TITLE
judge class is exist in class pool

### PR DESCRIPTION
**Pull request by 404NotFoundx**
i create a 'contains' method for ClassPool.
this method is i in issues 296 the question created.
it' can help we judge class exist in ClassPool

### CODE REVIEW

**Comment by chibash** [comment]
First, don't change the source-code format except the code block you really modify.
Second, 'contains' is not  a appropriate method name since this method only checks whether the class is contained in the on-memory cache.

**Comment by 404NotFoundx** [comment]
ok, i just habit format code.
you think this method name what should i use

**Comment by chibash** [comment]
I'm wondering about the purpose of this method.
Why do you want to know whether the given class is contained in the cache?
There is no guarantee that the cache contains all the classes accessible from that ClassPool.
Furthermore, `ClassPool` already provides `getCached(String)`.  Isn't it enough?

**Comment by 404NotFoundx** [comment]
i think you use the method name is error.
because regardless cache or native it' all exist ClassPool Isn't it.
you should give ClassPool a unite the judge method.

**Comment by 404NotFoundx** [comment]
like issues 296 the problem.
i have native class and ram class. it' all in ClassPool. i just want known exist in ClassPool not cache or native exist.
if you think i say is right. i will refork and dont format code submit.

**Comment by chibash** [comment]
I'm afraid that I don't understand what you want.
I think implementing `contains` or like is a bad idea.

**Comment by 404NotFoundx** [comment]
sorry maybe is my english not good let you dont undersand.
i want ClassPool have a unifled judge method.
like Map or String the contains method.

**Comment by 404NotFoundx** [comment]
if i add a class for ClassPool. i dont known this class from native or ram. i just known current ClassPool exist this class.
this happening i need use what method?

**Pull request closed without merging**
