### PR TITLE
New function CtClass#removeNestedClass(String) to remove a InnerClass

### PR DESCRIPTION
**Pull request by kuzukami**
Signature with formatted code.

### CODE REVIEW

**Comment by kuzukami** [comment]
Formatted by Eclipse with some setting optimization. If you need the format setting, I'll export the setting.

**Comment by chibash** [comment]
Thanks for the reformatting.  I looked at your code.
It should be fine to add remove() and clear() to InnerClassAttribute.

I'm not sure that adding removeNestedClass() to CtClass is a good idea because the semantics of the method is somewhat weird.  Some might think the method removes the inner class from ClassPool.   It is
unclear what will happen if removeNestedClass() is invoked when a method in the enclosing class refers to the removed inner class.  (I know nothing will happen but the class file will be just broken, though.)  I don't think the semantics of removeNestedClass() is predictable for average Java programmers.

So I'd like to suggest adding only remove() and clear() to InnerClassAttribute but not removeNestedClass().  Let me know your thought.

(One minor comment.  I think N and I should be constant values according to typical Java coding convention)

**Comment by kuzukami** [comment]
Thank you for your review of code.
As you said,  the method of CtClass#removeNestedClass() must be renamed because ti's confusing weather the class file is physically shrunk or the signature of inner class is shrunk.

I think the name CtClass#removeNestedClassSignagure() is better for this case.
The purpuse of this removal method for me is to make a simple shrinker in byte code level.

**Comment by chibash** [comment]
removeNestedClassSignature() is a better name but still I cannot accept it.

You don't directly modify gcConstPool etc. in CtClassType.  Get a ClassFile object by getClassFile(), modify the inner class attribute, and call rebuildClassFile() on the CtClassType object.

I've manually merged your pull request.  See this commit:
https://github.com/jboss-javassist/javassist/commit/2705a49f8fbe930cffa4358553e625071b3bf8ed

**Pull request closed without merging**
